version: "3.7"


services:
  postgres:
    build: './database'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=feeds
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d

  nats:
    image: nats-streaming:0.9.2
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    restart: always

  feed:
    build: '.'
    command: "feed-service"
    depends_on:
      - postgres
      - nats
      - elasticsearch
    ports:
      - "8080:8080"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=feeds
      - NATS_ADDRESS=nats:4222
  pusher:
    build: "."
    command: "pusher-service"
    depends_on:
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"
  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - feed
      - query
      - pusher